### ISSUE TITLE
Go Compilation Error in Initial

### ISSUE THREAD

**Issue by varunpalekar** [Gr1N/revel-gorm#10]
# Problem: 

When I have configured all things given in document, after then I have following error in starting. 

```
Go Compilation Error
The Go code github.com\Gr1N\revel-gorm\app\db.go does not compile: cannot use &dbm (type **gorm.DB) as type *gorm.DB in assignment

In github.com\Gr1N\revel-gorm\app\db.go (around line 41)

36: dbm, err := gorm.Open(driver, spec)
37: if err != nil {
38:     revel.ERROR.Fatal(err)
39: }
40:
41: DB = &dbm
42:
43: dbm.DB().Ping()
44: dbm.DB().SetMaxIdleConns(maxIdleConns)
45: dbm.DB().SetMaxOpenConns(maxOpenConns)
```

After debugging got that you are using reference of `dbm` which is  pointer of `gorm.DB`. 
`gorm.Open` function returns `*DB` and you are storing `**DB` or `&*DB` (of `gorm/main.go`) in variable `DB`. 
Real problem is we can't convert `*DB` to `**DB`.

**Comment by Gr1N** [comment]
My mistake, thanks for the fix
